input_namespace:
  metadata: processdenguedata
  fasta: splitgenomeandqc
output_namespace: out
params:
  "Number of sequences (local)": 10
  "Number of sequences (background)": 100
  "Time Interval": "Year"
  "Sampling Method": "Even"
  "Serotype": "denv4"
  "Serotype name": "Dengue_4"
