input_namespace: null
output_namespace: extractphylotree
acquiredata:
  name: AcquireData
  type: module
  snakefile: ../../AcquireData/workflow/Snakefile
  config:
    input_namespace: null
    output_namespace: acquiredata
    params:
      Sequence: virus genome taxon "Dengue Virus"
      Data format: virus-genome
      Date: 01/01/2010
      Command line arguments: []
processgenbankdata:
  name: ProcessGenbankData
  type: module
  snakefile: ../../../modules/ProcessGenbankData/workflow/Snakefile
  config:
    input_namespace: acquiredata
    output_namespace: processgenbankdata
    params:
      Start date: '2000-01-01T00:00:00.000Z'
      End date: '2023-12-24T00:00:00.000Z'
      Host: Homo sapiens
processdenguedata:
  name: ProcessDengueData
  type: module
  snakefile: ../../../modules/ProcessDengueData/workflow/Snakefile
  config:
    input_namespace: processgenbankdata
    output_namespace: processdenguedata
sequencealignment:
  name: SequenceAlignment
  type: module
  snakefile: ../../../modules/SequenceAlignment/workflow/Snakefile
  config:
    input_namespace: processdenguedata
    output_namespace: sequencealignment
splitgenomeandqc:
  name: SplitGenomeAndQC
  type: module
  snakefile: ../../../modules/SplitGenomeAndQC/workflow/Snakefile
  config:
    input_namespace: sequencealignment
    output_namespace: splitgenomeandqc
    params:
      WG Threshold: 0.29
      EG Threshold: 0.29
      Serotypes:
      - Dengue_1
      - Dengue_2
      - Dengue_3
      - Dengue_4
subsample_denv:
  name: Subsample_DENV
  type: module
  snakefile: ../../../modules/Subsample_DENV/workflow/Snakefile
  config:
    input_namespace:
      metadata: processdenguedata
      fasta: splitgenomeandqc
    output_namespace: subsample_denv
    params:
      Number of sequences (local): 10
      Number of sequences (background): 100
      Time Interval: Year
      Sampling Method: Even
      Serotypes:
      - Serotype: denv1
        Filename: Dengue_1
      - Serotype: denv2
        Filename: Dengue_2
      - Serotype: denv3
        Filename: Dengue_3
      - Serotype: denv4
        Filename: Dengue_4
reformatting:
  name: Reformatting
  type: module
  snakefile: ../../../modules/Reformatting/workflow/Snakefile
  config:
    input_namespace: subsample_denv
    output_namespace: reformatting
treebuilding:
  name: TreeBuilding
  type: module
  snakefile: ../../../modules/TreeBuilding/workflow/Snakefile
  config:
    input_namespace: reformatting
    output_namespace: treebuilding
    params:
      Model: GTR+F+I
      Command line arguments: -nt AUTO
treetime:
  name: TreeTime
  type: module
  snakefile: ../../../modules/TreeTime/workflow/Snakefile
  config:
    input_namespace:
      fasta: treebuilding
      metadata: reformatting
    output_namespace: treetime
    params:
      Clock filter IQD: 3
mutations:
  name: Mutations
  type: module
  snakefile: ../../../modules/Mutations/workflow/Snakefile
  config:
    input_namespace:
      fasta: treetime
      metadata: reformatting
    output_namespace: mutations
translation:
  name: Translation
  type: module
  snakefile: ../../../modules/Translation/workflow/Snakefile
  config:
    input_namespace:
      treetime: treetime
      mutations: mutations
    output_namespace: translation
mugration:
  name: Mugration
  type: module
  snakefile: ../../../modules/Mugration/workflow/Snakefile
  config:
    input_namespace:
      treetime: treetime
      subsample: reformatting
    output_namespace: mugration
export:
  name: Export
  type: module
  snakefile: ../../../modules/Export/workflow/Snakefile
  config:
    input_namespace:
      treetime: treetime
      translation: translation
      subsample: reformatting
      mutations: mutations
      mugrations: mugration
    output_namespace: export
extractphylotree:
  name: ExtractPhyloTree
  type: module
  snakefile: ../../../modules/ExtractPhyloTree/workflow/Snakefile
  config:
    input_namespace: export
    output_namespace: extractphylotree
treebreakdown:
  name: TreeBreakdown
  type: module
  snakefile: ../../../modules/TreeBreakdown/workflow/Snakefile
  config:
    input_namespace: extractphylotree
    output_namespace: treebreakdown
plotexportsandimports:
  name: PlotExportsAndImports
  type: module
  snakefile: ../../../modules/PlotExportsAndImports/workflow/Snakefile
  config:
    input_namespace: treebreakdown
    output_namespace: plotexportsandimports
    params:
      Country: Vietnam
