name: Check GRAPEVNE workflow (remote container build)

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "workflows/**"
  push:
    branches:
      - main
    paths:
      - "workflows/**"

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: workflows/Dengue/sources/build_packaged
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v3
      - name: Build GRAPEVNE container
        run: |
          ./build_container.sh
      - name: Launch GRAPEVNE container
        run: |
          ./launch_container.sh
